version: '3.6'

services:
  homeassistant:
    image: registry.services.alin.be/homeassistant-alin:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 190M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=8123
        - traefik.frontend.rule=Host:homeassistant.services.alin.be
        - traefik.backend=homeassistant
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
    volumes:
        - ./homeassistant:/config

networks:
  default:
    external:
      name: traefik-net
