version: '3.2'

services:
  homeassistant:
     image: homeassistant/home-assistant:0.49
     container_name: homeassistant
     ports:
        - "8123:8123"
     labels:
        - traefik.frontend.rule=Host:homeassistant.services.alin.be
        - traefik.backend=homeassistant
        - traefik.frontend.entryPoints=http,https
     volumes:
        - ./config:/config 
        - /etc/localtime:/etc/localtime:ro
     networks:
        - web
     devices:
        - /dev/snd:/dev/snd

networks:
  web:
    external:
      name: traefik_webgateway
